### ISSUE TITLE
Crash on Mirror Use

### ISSUE THREAD

**Issue by queenielawrens** [tired9494/Magic-Mirror#3]
Game Crashes when magic mirror is used.

Mod Versions:
Magic Mirror: 1.3.1
Fabric API: 0.37.0+1.17
Minecraft: 1.17.1

Log: 
```
[15:23:54] [Render thread/ERROR]: Parsing error loading recipe magic_mirror:magic_mirror_break
com.google.gson.JsonSyntaxException: Unknown item 'magic_mirror:magic_mirror_treasure'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1867$class_1868.method_8144(class_1867.java:98) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:83) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:2152) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1999) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java:1939) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:437) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:343) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:279) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:359) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:490) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1137) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[15:23:54] [Render thread/INFO]: Loaded 7 recipes
[15:23:54] [Render thread/INFO]: Loaded 1137 advancements
[15:23:55] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:23:55] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[15:23:55] [Server thread/INFO]: Generating keypair
[15:23:55] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:23:55] [Render thread/INFO]: Preparing spawn area: 0%
[15:23:55] [Render thread/INFO]: Preparing spawn area: 0%
[15:23:57] [Render thread/INFO]: Preparing spawn area: 0%
[15:23:57] [Render thread/INFO]: Preparing spawn area: 0%
[15:23:57] [Render thread/INFO]: Preparing spawn area: 0%
[15:23:57] [Render thread/INFO]: Preparing spawn area: 0%
[15:23:58] [Render thread/INFO]: Preparing spawn area: 54%
[15:23:58] [Render thread/INFO]: Preparing spawn area: 87%
[15:23:59] [Render thread/INFO]: Time elapsed: 3950 ms
[15:23:59] [Server thread/INFO]: QueenieLawrens joined the game
[15:23:59] [Netty Local Client IO #0/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 283.1 ?s
[15:23:59] [Server thread/INFO]: Saving and pausing game...
[15:23:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[15:24:00] [Render thread/INFO]: Loaded 0 advancements
[15:24:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[15:24:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[15:24:26] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3242.method_14357(class_3242.java:186) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10264()" because "â˜ƒ" is null
	at net.minecraft.class_5539.method_31606(class_5539.java:41) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1937.method_8320(class_1937.java:395) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1657.method_26091(class_1657.java:1473) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at github.tired9494.magic_mirror.MagicMirrorItem.method_7861(MagicMirrorItem.java:74) ~[%5B1.17%5D+Magic+Mirror+1.3.1.jar:?]
	at net.minecraft.class_1799.method_7910(class_1799.java:258) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1309.method_6040(class_1309.java:3072) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3222.method_6040(class_3222.java:1137) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1309.method_37119(class_1309.java:2956) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3222.method_37119(class_3222.java:1613) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1309.method_6076(class_1309.java:2943) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2309) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:466) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:212) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-minecraft-1.17.1-client.jar:?]
	... 6 more
[15:24:26] [Server thread/ERROR]: This crash report has been saved to: C:\Users\aweso\Documents\Setup\MultiMC\instances\1.17.1\.minecraft\crash-reports\crash-2021-07-20_15.24.26-server.txt
[15:24:26] [Server thread/INFO]: Stopping server
[15:24:26] [Server thread/INFO]: Saving players
[15:24:26] [Server thread/INFO]: Saving worlds
[15:24:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/20/21, 3:24 PM
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10264()" because "â˜ƒ" is null
	at net.minecraft.class_5539.method_31606(class_5539.java:41)
	at net.minecraft.class_1937.method_8320(class_1937.java:395)
	at net.minecraft.class_1657.method_26091(class_1657.java:1473)
	at github.tired9494.magic_mirror.MagicMirrorItem.method_7861(MagicMirrorItem.java:74)
	at net.minecraft.class_1799.method_7910(class_1799.java:258)
	at net.minecraft.class_1309.method_6040(class_1309.java:3072)
	at net.minecraft.class_3222.method_6040(class_3222.java:1137)
	at net.minecraft.class_1309.method_37119(class_1309.java:2956)
	at net.minecraft.class_3222.method_37119(class_3222.java:1613)
	at net.minecraft.class_1309.method_6076(class_1309.java:2943)
	at net.minecraft.class_1309.method_5773(class_1309.java:2309)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_3222.method_14226(class_3222.java:466)
	at net.minecraft.class_3244.method_18784(class_3244.java:212)
	at net.minecraft.class_2535.method_10754(class_2535.java:238)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_5539.method_31606(class_5539.java:41)
	at net.minecraft.class_1937.method_8320(class_1937.java:395)
	at net.minecraft.class_1657.method_26091(class_1657.java:1473)
	at github.tired9494.magic_mirror.MagicMirrorItem.method_7861(MagicMirrorItem.java:74)
	at net.minecraft.class_1799.method_7910(class_1799.java:258)
	at net.minecraft.class_1309.method_6040(class_1309.java:3072)
	at net.minecraft.class_3222.method_6040(class_3222.java:1137)
	at net.minecraft.class_1309.method_37119(class_1309.java:2956)
	at net.minecraft.class_3222.method_37119(class_3222.java:1613)
	at net.minecraft.class_1309.method_6076(class_1309.java:2943)
	at net.minecraft.class_1309.method_5773(class_1309.java:2309)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 97
	Entity Name: QueenieLawrens
	Entity's Exact location: 12.95, 64.00, -5.70
	Entity's Block location: World: (12,64,-6), Section: (at 12,0,10 in 0,4,-1; chunk contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:466)
	at net.minecraft.class_3244.method_18784(class_3244.java:212)
	at net.minecraft.class_2535.method_10754(class_2535.java:238)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by tired9494** [comment]
I can't replicate this issue but could you check if this version fixes it: https://github.com/tired9494/Magic-Mirror/releases/download/1.3.1b/magic_mirror-1.3.1b.jar

If not, does this happen every time you use the mirror and in every world? Are any of your config options not set to default? Is there anything unusual about your spawnpoint (e.g. surrounded by blocks, near height limit, etc)?

**Comment by queenielawrens** [comment]
That fixed it! 
As for the original crash, it happened in multiple worlds with no config changes. I opened the world, moved a few blocks, and tried to use the mirror. I hadn't set a spawnpoint (I'd forgotten that part of the mod).
